# Generated by Django 5.0.7 on 2024-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0002_procedure_servicecategory_delete_test1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
