# Generated by Django 5.0.7 on 2024-10-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0003_procedure_name_en_procedure_name_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureTEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('text_uk', models.TextField(blank=True, max_length=1000, null=True)),
                ('text_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappback.servicecategory')),
            ],
        ),
    ]
