# Generated by Django 5.0.7 on 2024-10-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0004_proceduretest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='proceduretest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappback.categorytest'),
        ),
    ]
