# Generated by Django 5.0.7 on 2024-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0005_categorytest_alter_proceduretest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytest',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categorytest',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
