# Generated by Django 5.0.7 on 2024-10-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0006_categorytest_title_en_categorytest_title_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduretest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='myappback.categorytest'),
        ),
        migrations.AlterField(
            model_name='proceduretest',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proceduretest',
            name='text_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proceduretest',
            name='text_uk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
