# Generated by Django 5.0.7 on 2024-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0007_alter_proceduretest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduretest',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proceduretest',
            name='text_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proceduretest',
            name='text_uk',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
