# Generated by Django 5.0.7 on 2024-10-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0008_alter_proceduretest_text_alter_proceduretest_text_en_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryTest',
            new_name='CategoryActivity',
        ),
        migrations.RenameModel(
            old_name='ProcedureTEst',
            new_name='ProcedureActivity',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
