# Generated by Django 5.0.7 on 2024-10-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0009_rename_categorytest_categoryactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('about_myself', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('information', models.CharField(max_length=255)),
                ('image_info', models.ImageField(blank=True, null=True, upload_to='doctors/image/')),
                ('education', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('work_method', models.CharField(blank=True, max_length=255, null=True)),
                ('work_directions', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_development', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_professional_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('specialty', models.ManyToManyField(related_name='doctors', to='myappback.specialty')),
            ],
        ),
    ]
