# Generated by Django 5.0.7 on 2024-10-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0011_remove_doctors_specialty_doctors_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='about_myself_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='about_myself_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='additional_professional_activity_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='additional_professional_activity_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='education_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='education_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='experience_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='experience_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='image_info_en',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/image/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='image_info_uk',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/image/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='information_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='information_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo_en',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo_uk',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='professional_development_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='professional_development_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='skills_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='skills_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialization_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialization_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty_en',
            field=models.CharField(default='Доктор', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty_uk',
            field=models.CharField(default='Доктор', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_directions_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_directions_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_method_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_method_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
