# Generated by Django 5.0.7 on 2024-10-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0012_doctors_about_myself_en_doctors_about_myself_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='image_info_en',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='image_info_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='photo_en',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='photo_uk',
        ),
    ]
