# Generated by Django 5.0.7 on 2024-10-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0014_alter_doctors_about_myself_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
