# Generated by Django 5.0.7 on 2024-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0015_alter_doctors_name_alter_doctors_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryactivity',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='about_myself_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='additional_professional_activity_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='education_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='experience_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='information_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='professional_development_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='skills_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='specialization_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='specialty_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='work_directions_uk',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='work_method_uk',
        ),
        migrations.RemoveField(
            model_name='procedureactivity',
            name='text_uk',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='additional_professional_activity',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='additional_professional_activity_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='professional_development',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='professional_development_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='skills',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='skills_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_directions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_directions_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
