# Generated by Django 5.0.7 on 2024-10-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0017_categoryactivity_title_uk_doctors_about_myself_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='experience',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='experience_uk',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
