# Generated by Django 5.0.7 on 2024-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0018_alter_doctors_experience_alter_doctors_experience_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='work_method',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_method_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_method_uk',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
