# Generated by Django 5.0.7 on 2024-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0019_alter_doctors_work_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='education',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='education_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='education_uk',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
