# Generated by Django 5.0.7 on 2024-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappback', '0020_alter_doctors_education_alter_doctors_education_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='photo_small',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/'),
        ),
    ]
